apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgresqlbackups3
spec:
  schedule: "0 0 * * *" # This runs every minute; modify as needed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: S3_ACCESS_KEY_ID
              value: {{ .Values.s3.accessKeyId }}
            - name: S3_SECRET_ACCESS_KEY
              value: {{ .Values.s3.secretAccessKey }}
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint }}
            - name: S3_PREFIX
              value: {{ .Values.s3.prefix }}
          restartPolicy: OnFailure
