apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresqlbackups3
spec:
  schedule: "0 0 * * *" # This runs every minute; modify as needed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.database | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: S3_ACCESS_KEY_ID
              value: {{ .Values.s3.accessKeyId | quote }}
            - name: S3_SECRET_ACCESS_KEY
              value: {{ .Values.s3.secretAccessKey | quote }}
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            {{- if .Values.s3.endpoint }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint | quote }}
            {{- end }}
            - name: S3_PREFIX
              value: {{ .Values.s3.prefix | quote }}
            - name: S3_REGION
              value: {{ .Values.s3.region | quote }}

          restartPolicy: OnFailure
